blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from .views import BlogPostCreateView, BlogPostDetailView, BlogPostListView, BlogPostUpdateView, BlogPostDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path("", BlogPostListView.as_view(), name="blogpost_list"),
    path("<int:pk>/", BlogPostDetailView.as_view(), name="blogpost_detail"),
    path("new/", BlogPostCreateView.as_view(), name="blogpost_create"),
    path("<int:pk>/edit/", BlogPostUpdateView.as_view(), name="blogpost_update"),
    path("<int:pk>/delete/", BlogPostDeleteView.as_view(), name="blogpost_delete"),

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("mailing/", include('mailing.urls', namespace="mailing")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from . import views
from django.urls import path
from .views import AboutView, ContactsView
from .views import (
    RecipientListView, RecipientDetailView, RecipientCreateView, RecipientUpdateView, RecipientDeleteView,
    MessageListView, MessageDetailView, MessageCreateView, MessageUpdateView, MessageDeleteView,
    MailingListView, MailingDetailView, MailingCreateView, MailingUpdateView, MailingDeleteView, send_mailing
)

app_name = "mailing"


urlpatterns = [
    path('', views.index, name='index'), # Главная страница приложения
    path('about/', AboutView.as_view(), name='about'), # Страница О нас
    path('contacts/', ContactsView.as_view(), name='contacts'), # Страница контактов
    # URLs для модели Recipient
    path('recipients/', RecipientListView.as_view(), name='recipient_list'),
    path('recipients/<int:pk>/', RecipientDetailView.as_view(), name='recipient_detail'),
    path('recipients/create/', RecipientCreateView.as_view(), name='recipient_create'),
    path('recipients/<int:pk>/edit/', RecipientUpdateView.as_view(), name='recipient_update'),
    path('recipients/<int:pk>/delete/', RecipientDeleteView.as_view(), name='recipient_delete'),
    # URLs для модели Message
    path('messages/', MessageListView.as_view(), name='message_list'),
    path('messages/<int:pk>/', MessageDetailView.as_view(), name='message_detail'),
    path('messages/create/', MessageCreateView.as_view(), name='message_create'),
    path('messages/<int:pk>/edit/', MessageUpdateView.as_view(), name='message_edit'),
    path('messages/<int:pk>/delete/', MessageDeleteView.as_view(), name='message_delete'),
    # URLs для модели Mailing
    path('mailings/', MailingListView.as_view(), name='mailing_list'),
    path('mailings/<int:pk>/', MailingDetailView.as_view(), name='mailing_detail'),
    path('mailings/create/', MailingCreateView.as_view(), name='mailing_create'),
    path('mailings/<int:pk>/edit/', MailingUpdateView.as_view(), name='mailing_edit'),
    path('mailings/<int:pk>/delete/', MailingDeleteView.as_view(), name='mailing_delete'),
    path('mailings/<int:pk>/send/', send_mailing, name='mailing_send'), # Ручная отправка рассылки

]

mailing/models.py
from django.db import models
from django.utils.timezone import now

class Recipient(models.Model):
    """Модель для хранения информации о клиентах"""
    email = models.EmailField(unique=True)
    full_name = models.CharField(max_length=100)
    comment = models.TextField(blank=True, null=True)

    class Meta:
        verbose_name = 'Получатель'
        verbose_name_plural = 'Получатели'

    def __str__(self):
        return self.full_name


class Message(models.Model):
    """Модель для хранения сообщений"""
    subject = models.CharField(max_length=255)
    body = models.TextField()

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'

    def __str__(self):
        return self.subject


class Mailing(models.Model):
    """Модель управления рассылками"""
    STATUS_CHOICES = [
        ('created', 'Создана'),
        ('started', 'Запущена'),
        ('finished', 'Завершена'),
    ]

    send_time_start = models.DateTimeField(verbose_name="Дата и время начала отправки")
    send_time_end = models.DateTimeField(verbose_name="Дата и время окончания отправки")
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='created', verbose_name="Статус")
    message = models.ForeignKey('Message', on_delete=models.CASCADE, verbose_name="Сообщение")
    recipients = models.ManyToManyField('Recipient', verbose_name="Получатели")

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'

    def __str__(self):
        return f"Рассылка: {self.message.subject} ({self.get_status_display()})"

    def update_status(self):
        """Обновляет статус рассылки на основе времени"""
        current_time = now()
        if self.status == 'created' and current_time >= self.send_time_start:
            self.status = 'started'
        if self.status == 'started' and current_time >= self.send_time_end:
            self.status = 'finished'
        self.save()


class MailingAttempt(models.Model):
    """Модель для попыток рассылки"""

    STATUS_CHOICES = [
        ('success', 'Успешно'),
        ('failed', 'Не успешно'),
    ]

    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, related_name='attempts', verbose_name="Рассылка")
    timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата и время попытки")
    status = models.CharField(max_length=7, choices=STATUS_CHOICES, verbose_name="Статус")
    server_response = models.TextField(verbose_name="Ответ почтового сервера")

    class Meta:
        verbose_name = 'Попытка рассылки'
        verbose_name_plural = 'Попытки рассылки'

    def __str__(self):
        return f"Попытка для рассылки '{self.mailing}' - {self.get_status_display()} в {self.timestamp:%Y-%m-%d %H:%M:%S}"

mailing/views.py
from django.urls import reverse_lazy
from django.shortcuts import render, get_object_or_404
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Recipient, Message, Mailing, MailingAttempt
from django.core.mail import send_mail



class AboutView(TemplateView):
    template_name = 'mailing/about.html'


class ContactsView(TemplateView):
    template_name = 'mailing/contacts.html'


# Представления для модели Recipient
class RecipientListView(ListView):
    model = Recipient
    template_name = 'mailing/recipient_list.html'
    context_object_name = 'recipients'

class RecipientDetailView(DetailView):
    model = Recipient
    template_name = 'mailing/recipient_detail.html'
    context_object_name = 'recipient'

class RecipientCreateView(CreateView):
    model = Recipient
    template_name = 'mailing/recipient_form.html'
    fields = ['email', 'full_name', 'comment']
    success_url = reverse_lazy('mailing:recipient_list')

class RecipientUpdateView(UpdateView):
    model = Recipient
    template_name = 'mailing/recipient_form.html'
    fields = ['email', 'full_name', 'comment']
    success_url = reverse_lazy('mailing:recipient_list')

class RecipientDeleteView(DeleteView):
    model = Recipient
    template_name = 'mailing/recipient_confirm_delete.html'
    success_url = reverse_lazy('mailing:recipient_list')

# Представления для модели Message
class MessageListView(ListView):
    model = Message
    template_name = 'mailing/message_list.html'
    context_object_name = 'messages'

class MessageDetailView(DetailView):
    model = Message
    template_name = 'mailing/message_detail.html'
    context_object_name = 'message'

class MessageCreateView(CreateView):
    model = Message
    template_name = 'mailing/message_form.html'
    fields = ['subject', 'body']
    success_url = reverse_lazy('mailing:message_list')

class MessageUpdateView(UpdateView):
    model = Message
    template_name = 'mailing/message_form.html'
    fields = ['subject', 'body']
    success_url = reverse_lazy('mailing:message_list')

class MessageDeleteView(DeleteView):
    model = Message
    template_name = 'mailing/message_confirm_delete.html'
    success_url = reverse_lazy('mailing:message_list')

# Представления для модели Mailing
class MailingListView(ListView):
    model = Mailing
    template_name = 'mailing/mailing_list.html'
    context_object_name = 'mailings'

class MailingDetailView(DetailView):
    model = Mailing
    template_name = 'mailing/mailing_detail.html'
    context_object_name = 'mailing'

class MailingCreateView(CreateView):
    model = Mailing
    fields = ['send_time_start', 'send_time_end', 'status', 'message', 'recipients']
    template_name = 'mailing/mailing_form.html'
    success_url = reverse_lazy('mailing:mailing_list')

class MailingUpdateView(UpdateView):
    model = Mailing
    fields = ['send_time_start', 'send_time_end', 'status', 'message', 'recipients']
    template_name = 'mailing/mailing_form.html'
    success_url = reverse_lazy('mailing:mailing_list')

class MailingDeleteView(DeleteView):
    model = Mailing
    template_name = 'mailing/mailing_confirm_delete.html'
    success_url = reverse_lazy('mailing:mailing_list')


def send_mailing(request, pk):
    """Отправка рассылки вручную"""
    mailing = get_object_or_404(Mailing, pk=pk)
    recipients = mailing.recipients.all()

    for recipient in recipients:
        try:
            send_mail(
                subject=mailing.message.subject,
                message=mailing.message.content,
                from_email='EasyMail@example.com',
                recipient_list=[recipient.email],
            )
            MailingAttempt.objects.create(
                mailing=mailing,
                status='success',
                server_response="Сообщение отправлено успешно"
            )
        except Exception as e:
            MailingAttempt.objects.create(
                mailing=mailing,
                status='failed',
                server_response=str(e)
            )

    mailing.update_status()
    return render(request, 'mailing/mailing_send_confirmation.html', {'mailing': mailing})



def index(request):
    # Подсчёт количества всех рассылок
    total_mailings = Mailing.objects.count()

    # Подсчёт количества активных рассылок (со статусом 'Запущена')
    active_mailings = Mailing.objects.filter(status='started').count()

    # Подсчёт количества уникальных получателей
    unique_recipients = Recipient.objects.distinct().count()

    context = {
        'total_mailings': total_mailings,
        'active_mailings': active_mailings,
        'unique_recipients': unique_recipients,
    }
    return render(request, 'mailing/index.html', context)

mailing/templates/mailing/about.html
{% extends 'mailing/base.html' %}

{% block title %}О нас - EasyMail{% endblock %}

{% block header %}О нас{% endblock %}

{% block subheader %}Узнайте больше о сервисе EasyMail{% endblock %}

{% block content %}
<div class="container">
    <p>EasyMail — это простой и удобный сервис для создания и управления email-рассылками.</p>
</div>
{% endblock %}

mailing/templates/mailing/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Сервис email-рассылок EasyMail {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>

    {% include 'mailing/includes/header.html' %}

    <header>
        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">{% block header %}EasyMail{% endblock %}</h1>
        <p class="lead">{% block subheader %}Простой и удобный сервис email-рассылок{% endblock %}</p>
        </div>

    </header>

    <main>
        {% block content %}{% endblock %}
    </main>

    {% include "mailing/includes/footer.html" %}

    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

mailing/templates/mailing/contacts.html
{% extends 'mailing/base.html' %}

{% block title %}Контакты - EasyMail{% endblock %}

{% block header %}Контакты{% endblock %}

{% block subheader %}Мы на связи. Рады вам!{% endblock %}

{% block content %}
<div style="padding-left: 20px !important;">
    <p>Если у вас есть вопросы или предложения, вы можете связаться с нами:</p>
    <ul>
        <li>Email: </li>
        <li>Телефон: </li>
        <li>Адрес: </li>
    </ul>
</div>
{% endblock %}

mailing/templates/mailing/index.html
{% extends "mailing/base.html" %}

{% load static %}

{% block title %}Главная страница{% endblock %}
{% block content %}
<div style="margin-left: 20px;">
<h2>Статистика рассылок EasyMail:</h2>
<p>Всего рассылок: {{ total_mailings }}</p>
<p>Активных рассылок: {{ active_mailings }}</p>
<p>Уникальных получателей: {{ unique_recipients }}</p>
</div>
{% endblock %}

mailing/templates/mailing/mailing_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block title %}Удалить рассылку{% endblock %}
{% block header %}Удалить рассылку{% endblock %}

{% block content %}
<div class="container mt-4 text-center">
    {% if recipient.created_by == user %}
        <p>Вы уверены, что хотите удалить рассылку "{{ mailing }}"?</p>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Удалить</button>
            <a href="{% url 'mailing:mailing_list' %}" class="btn btn-secondary">Отмена</a>
        </form>
    {% endif %}
</div>
{% endblock %}

mailing/templates/mailing/mailing_detail.html
{% extends 'mailing/base.html' %}

{% block title %}Детали рассылки{% endblock %}
{% block header %}Детали рассылки{% endblock %}

{% block content %}
<div style="padding-left: 20px !important;">
    {% if is_manager or mailing.created_by == user %}
        <h2>{{ mailing }}</h2>
        <p><strong>Начало отправки:</strong> {{ mailing.send_time_start }}</p>
        <p><strong>Конец отправки:</strong> {{ mailing.send_time_end }}</p>
        <p><strong>Статус:</strong> {{ mailing.get_status_display }}</p>
        <p><strong>Сообщение:</strong> {{ mailing.message }}</p>
        <p><strong>Получатели:</strong> {{ mailing.recipients.all|join:", " }}</p>
    {% endif %}

    {% if mailing.created_by == user %}
        <a href="{% url 'mailing:mailing_edit' mailing.id %}" class="btn btn-outline-warning">Редактировать</a>
        <a href="{% url 'mailing:mailing_delete' mailing.id %}" class="btn btn-outline-danger">Удалить</a>
    {% endif %}

    {% if mailing.created_by == user and mailing.status == "created" %}
        <a href="{% url 'mailing:mailing_send_confirmation' mailing.id %}" class="btn btn-outline-success">Отправить рассылку</a>
    {% endif %}

        <a href="{% url 'mailing:mailing_list' %}" class="btn btn-outline-primary">Назад к списку</a>
</div>
{% endblock %}

mailing/templates/mailing/mailing_send_confirmation.html
{% extends 'mailing/base.html' %}

{% block title %}Подтвердить отправку рассылки{% endblock %}
{% block header %}Подтверждение отправки{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2>Вы уверены, что хотите отправить эту рассылку?</h2>
    <div class="card my-4">
        <div class="card-body">
            <h5 class="card-title">Сообщение: {{ mailing.message.subject }}</h5>
            <p class="card-text"><strong>Текст сообщения:</strong> {{ mailing.message.content }}</p>
            <p class="card-text"><strong>Получатели:</strong> {{ mailing.recipients.all|join:", " }}</p>
            <p class="card-text"><strong>Дата начала отправки:</strong> {{ mailing.send_time_start }}</p>
            <p class="card-text"><strong>Дата окончания отправки:</strong> {{ mailing.send_time_end }}</p>
        </div>
    </div>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Отправить</button>
        <a href="{% url 'mailing:mailing_list' %}" class="btn btn-secondary">Отмена</a>
    </form>
</div>
{% endblock %}

mailing/templates/mailing/message_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block title %}Удалить сообщение{% endblock %}
{% block header %}Подтвердите удаление{% endblock %}
{% block content %}
<div class="container">
    {% if message.created_by == request.user %}
        <p>Вы уверены, что хотите удалить сообщение "{{ message.subject }}"?</p>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-outline-danger">Удалить</button>
            <a href="{% url 'mailing:message_list' %}" class="btn btn-outline-secondary">Отмена</a>
        </form>
    {% endif %}
{% endblock %}

mailing/templates/mailing/message_detail.html
{% extends 'mailing/base.html' %}

{% block title %}Детали сообщения{% endblock %}
{% block header %}Детали сообщения{% endblock %}
{% block content %}
<div style="padding-left: 20px !important;">
    {% if message.created_by == request.user %}
    <h2>{{ message.subject }}</h2>
    <p>{{ message.body }}</p>
    <div class="mt-5">
        <a href="{% url 'mailing:message_edit' message.id %}" class="btn btn-outline-warning">Редактировать</a>
        <a href="{% url 'mailing:message_delete' message.id %}" class="btn btn-outline-danger">Удалить</a>
    </div>
    {% else %}
    <p>У вас нет доступа к этой рассылке.</p>
    {% endif %}
    <a href="{% url 'mailing:message_list' %}" class="btn btn-outline-primary">Назад к списку сообщений</a>
</div>
{% endblock %}

mailing/templates/mailing/message_form.html
{% extends 'mailing/base.html' %}

{% block title %}Создать/Редактировать сообщение{% endblock %}
{% block header %}{{ view.object.pk|yesno:"Редактировать,Создать" }} сообщение{% endblock %}
{% block content %}
<div class="container mt-4">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-outline-primary">Сохранить</button>
        <a href="{% url 'mailing:message_list' %}" class="btn btn-outline-secondary">Отмена</a>
    </form>
{% endblock %}

mailing/templates/mailing/recipient_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block title %}Удалить получателя{% endblock %}
{% block header %}Удаление получателя{% endblock %}
{% block subheader %}Вы уверены, что хотите удалить этого получателя?{% endblock %}

{% block content %}
<div class="container">
    {% if recipient.created_by == user %}
    <p>Вы действительно хотите удалить получателя <strong>{{ recipient.full_name }}</strong> ({{ recipient.email }})?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Удалить</button>
        <a href="{% url 'mailing:recipient_list' %}" class="btn btn-secondary">Отмена</a>
    </form>
    {% endif %}
</div>
{% endblock %}

mailing/templates/mailing/recipient_form.html
{% extends 'mailing/base.html' %}

{% block title %}Создание получателя{% endblock %}
{% block header %}Создать нового получателя{% endblock %}
{% block subheader %}Введите данные нового получателя{% endblock %}

{% block content %}
<div class="container mt-4">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Сохранить</button>
        <a href="{% url 'mailing:recipient_list' %}" class="btn btn-secondary">Отмена</a>
    </form>
</div>
{% endblock %}

mailing/templates/mailing/recipient_list.html
{% extends 'mailing/base.html' %}

{% block title %}Список получателей{% endblock %}
{% block header %}Получатели email-рассылок{% endblock %}
{% block subheader %}Список всех получателей email-рассылок в системе EasyMail{% endblock %}

{% block content %}
<div class="container">
    <ul class="list-group">
        {% if is_manager %}
        {% for recipient in recipients %}
            <li class="list-group-item">
                <a href="{% url 'mailing:recipient_detail' recipient.pk %}">{{ recipient.full_name }}</a> - {{ recipient.email }}
            <span class="badge bg-info">Добавлен: {{ recipient.created_by.email }}</span>
            </li>
        {% endfor %}
    </ul>
    {% else %}
        <a href="{% url 'mailing:recipient_create' %}" class="btn btn-outline-success mb-3">Добавить получателя</a>
    <ul class="list-group">
            {% for recipient in recipients %}
                <li class="list-group-item">
                    <a href="{% url 'mailing:recipient_detail' recipient.pk %}">{{ recipient.full_name }}</a> - {{ recipient.email }}
                </li>
            {% endfor %}
        </ul>
    {% endif %}
</div>
{% endblock %}

mailing/templates/mailing/recipient_update.html
{% extends "base.html" %}

{% block title %}Редактировать получателя{% endblock %}

{% block content %}
<h2>Редактировать получателя</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    {% if recipient.created_by == user %}
    <button type="submit" class="btn btn-primary">Сохранить изменения</button>
    <a href="{% url 'recipient_list' %}" class="btn btn-secondary">Отмена</a>
    {% endif %}
</form>
{% endblock %}