blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from .views import BlogPostCreateView, BlogPostDetailView, BlogPostListView, BlogPostUpdateView, BlogPostDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path("", BlogPostListView.as_view(), name="blogpost_list"),
    path("<int:pk>/", BlogPostDetailView.as_view(), name="blogpost_detail"),
    path("new/", BlogPostCreateView.as_view(), name="blogpost_create"),
    path("<int:pk>/edit/", BlogPostUpdateView.as_view(), name="blogpost_update"),
    path("<int:pk>/delete/", BlogPostDeleteView.as_view(), name="blogpost_delete"),

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("mailing/", include('mailing.urls', namespace="mailing")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from . import views
from django.urls import path
from .views import AboutView, ContactsView
from .views import (
    RecipientListView, RecipientDetailView, RecipientCreateView, RecipientUpdateView, RecipientDeleteView,
    MessageListView, MessageDetailView, MessageCreateView, MessageUpdateView, MessageDeleteView,
    MailingListView, MailingDetailView, MailingCreateView, MailingUpdateView, MailingDeleteView, send_mailing
)

app_name = "mailing"


urlpatterns = [
    path('', views.index, name='index'), # Главная страница приложения
    path('about/', AboutView.as_view(), name='about'), # Страница О нас
    path('contacts/', ContactsView.as_view(), name='contacts'), # Страница контактов
    # URLs для модели Recipient
    path('recipients/', RecipientListView.as_view(), name='recipient_list'),
    path('recipients/<int:pk>/', RecipientDetailView.as_view(), name='recipient_detail'),
    path('recipients/create/', RecipientCreateView.as_view(), name='recipient_create'),
    path('recipients/<int:pk>/edit/', RecipientUpdateView.as_view(), name='recipient_update'),
    path('recipients/<int:pk>/delete/', RecipientDeleteView.as_view(), name='recipient_delete'),
    # URLs для модели Message
    path('messages/', MessageListView.as_view(), name='message_list'),
    path('messages/<int:pk>/', MessageDetailView.as_view(), name='message_detail'),
    path('messages/create/', MessageCreateView.as_view(), name='message_create'),
    path('messages/<int:pk>/edit/', MessageUpdateView.as_view(), name='message_edit'),
    path('messages/<int:pk>/delete/', MessageDeleteView.as_view(), name='message_delete'),
    # URLs для модели Mailing
    path('mailings/', MailingListView.as_view(), name='mailing_list'),
    path('mailings/<int:pk>/', MailingDetailView.as_view(), name='mailing_detail'),
    path('mailings/create/', MailingCreateView.as_view(), name='mailing_create'),
    path('mailings/<int:pk>/edit/', MailingUpdateView.as_view(), name='mailing_edit'),
    path('mailings/<int:pk>/delete/', MailingDeleteView.as_view(), name='mailing_delete'),
    path('mailings/<int:pk>/send/', send_mailing, name='mailing_send'), # Ручная отправка рассылки

]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from .views import RegisterView, UserLoginView, UserProfileUpdateView, UserProfileView

app_name = 'users'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('profile/edit/', UserProfileUpdateView.as_view(), name='profile_edit'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name="Email")
    avatar = models.ImageField(upload_to="avatars/", blank=True, null=True, verbose_name="Аватар")
    phone = models.CharField(
        max_length=20, verbose_name="Телефон", blank=True, null=True, help_text="Укажите номер телефона"
    )
    country = models.CharField(max_length=50, verbose_name="Страна", blank=True, null=True, help_text="Укажите страну")

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

    def __str__(self):
        return self.email

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

from .models import User


class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(label='Email', required=True)

    class Meta:
        model = User
        fields = ['email', 'password1', 'password2']


class UserLoginForm(AuthenticationForm):
    username = forms.EmailField(label='Email')


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email', 'avatar', 'phone', 'country']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['email'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Введите ваш email'})
        self.fields['phone'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Введите номер телефона'})
        self.fields['country'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Выберите страну'})
        self.fields['avatar'].widget.attrs.update({'class': 'form-control-file', 'accept': 'image/*'})

        for field in self.fields.values():
            if 'class' not in field.widget.attrs:
                field.widget.attrs['class'] = 'form-control'
            else:
                field.widget.attrs['class'] += ' form-control'

users/views.py
from django.conf import settings
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy
from django.views.generic import DetailView, FormView, UpdateView
from django.shortcuts import render, redirect

from .forms import UserLoginForm, UserProfileForm, UserRegistrationForm
from .models import User


class RegisterView(FormView):
    template_name = 'users/register.html'
    form_class = UserRegistrationForm
    success_url = reverse_lazy('mailing:index')

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        user.save()
        return redirect(self.success_url)

        # Отправка приветственного письма
        send_mail(
            subject="Добро пожаловать!",
            message="Спасибо за регистрацию! Добро пожаловать в наш сервис!",
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[user.email],
            fail_silently=False,
        )

        return super().form_valid(form)


class UserLoginView(LoginView):
    authentication_form = UserLoginForm
    template_name = 'users/login.html'
    success_url = reverse_lazy('mailing:index')


class UserLogoutView(LogoutView):
    next_page = reverse_lazy('mailing:index')


class UserProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserProfileForm
    template_name = 'users/profile_edit.html'
    success_url = reverse_lazy('mailing:index')

    def get_object(self, queryset=None):
        return self.request.user  # Пользователь может изменять только свой профиль


class UserProfileView(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'users/profile.html'

    def get_object(self):
        return self.request.user

@login_required
def profile_edit(request):
    user = request.user
    form = UserProfileForm(instance=user)

    if request.method == "POST":
        form = UserProfileForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return redirect("users:profile")

    return render(request, "users/profile_edit.html", {"form": form})

users/templates/users/login.html
{% extends "mailing/base.html" %}

{% block content %}
<h2>Вход</h2>
<form method="post" action="{% url 'users:login' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Войти</button>
</form>
<p>Нет аккаунта? <a href="{% url 'users:register' %}">Регистрация</a></p>
{% endblock %}

users/templates/users/logout.html
{% extends "mailing/base.html" %}

{% block content %}
<h2>Выход из системы</h2>
<p>Вы уверены, что хотите выйти?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit">Выйти</button>
</form>
<a href="{% url 'mailing:index' %}">Отмена</a>
{% endblock %}

users/templates/users/profile.html
{% extends "mailing/base.html" %}

{% block content %}
<div style="margin-left: 20px;">
<h2>Ваш профиль</h2>
<ul>
    <p><strong>Email:</strong> {{ user.email }}</p>
    <p><strong>Телефон:</strong> {{ user.phone }}</p>
    <p><strong>Страна:</strong> {{ user.country }}</p>

    <a href="{% url 'mailing:mailing_statistics' %}"><strong>Статистика ваших рассылок</strong></a>


    {% if user.avatar %}
        <p><strong>Аватар:</strong></p>
        <img src="{{ user.avatar.url }}" alt="Avatar" width="150">
    {% endif %}
    <div class="mt-4">
    <a href="{% url 'users:profile_edit' %}">Редактировать профиль</a>
    </div>
    <div class="mt-2">
    <a href="{% url 'users:logout' %}">Выйти</a>
    </div>
</ul>
{% endblock %}

users/templates/users/profile_edit.html
{% extends "mailing/base.html" %}

{% block content %}
<h2>Редактирование профиля</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить изменения</button>
</form>
<a href="{% url 'users:profile' %}">Назад в профиль</a>
{% endblock %}

users/templates/users/register.html
{% extends "mailing/base.html" %}

{% block content %}
<h2>Регистрация</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Зарегистрироваться</button>
</form>
<p>Уже зарегистрированы? <a href="{% url 'users:login' %}">Войти</a></p>
{% endblock %}